services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-dev
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - N8N_BASIC_AUTH_ACTIVE=false
    volumes:
      - /var/opt/n8n:/home/node/data
    user: "1000:1000"
