services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    env_file:
      - .env
    user: '${UID}:${GID}'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Europe/Madrid}
      - TZ=${GENERIC_TIMEZONE:-Europe/Madrid}
    ports:
      - '${N8N_PORT:-5678}:5678'
    volumes:
      - ${N8N_USER_FOLDER}:/home/node/.n8n
