services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    env_file:
      - .env
    ports:
      - "${N8N_PORT:-5678}:5678"
    volumes:
      - ${N8N_USER_FOLDER}:/home/node/.n8n
